name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0.0, v20.15.10

permissions:
  contents: write # This is required for creating releases

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # This ensures all tags are fetched

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build and publish
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_root: my-app
          release: ${{startsWith(github.ref, 'refs/tags/v') }}
          args: --publish always --config.publish.vPrefixedTagName=true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Release Notes
        uses: softprops/action-gh-release@v1
        with:
          name: Electron App ${{ github.ref_name }}
          body: |
            ## Release Notes

            Changes in this version:
            - Feature improvements
            - Bug fixes
          token: ${{ secrets.GITHUB_TOKEN }}
